run:
	make rebuild
	frame

rebuild:
	make clean
	make build

clean:
	del frame.com
	del frame.obj
	del frame.lst
	del frame.map

build: frame.com

frame.com: frame.obj
	tlink /t /v frame.obj

frame.obj:
	tasm /la frame.asm
